/**
 * Components - Footer
 */

import React from 'react';
import { DateTime } from 'luxon';

import Container from './Container';

import '../styles/02-components/_footer.scss';

const Footer = () => (
    <footer className="footer">
        <Container>
            <p>Icons from <a href="https://icomoon.io/app/" target="_blank" rel="noopener noreferrer">IcoMoon</a> and <a href="https://material.io/icons/" target="_blank" rel="noopener noreferrer">Material Design</a>.</p>
            <p>Built with <a href="https://www.gatsbyjs.org" target="_blank" rel="noopener noreferrer">Gatsby</a>. Site name generated by the <a href="http://www.hipsterbusiness.name/" target="_blank" rel="noopener noreferrer">Hipster Business Name Generator</a>.</p>
            <p>&copy; Lyndsey Herbert {DateTime.local().toFormat('yyyy')}. All rights reserved.</p>
        </Container>
    </footer>
);

export default Footer;
